swagger: "2.0"
info:
  description: |
    This finds the length of a string. It's AWESOME!
  version: "1.0.0"
  title: strlen
  contact:
    name: travis
    email: travis.simon@nicta.com.au
  license:
    name: GPL 3.0
    url: http://www.gnu.org/licenses/gpl-3.0.en.html
host: strlen
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /strlen/{string}:
    get:
      tags:
        - string
      summary: Find the length of a string
      description: Returns length of a string
      operationId: getStringLength
      produces:
        - application/json
      parameters:
        - in: path
          name: string
          description: string whose length is unknown
          required: true
          type: string
      responses:
        "200":
          description: successful operation
          schema:
            type: integer
            format: int64
